#%RAML 1.0 DataType


properties:
  EmployeNumber:
    type: string
    description: SFDC User Employee Number
    required: true
  Name:
    type: string
    description: SFDC User Name
    required: true
  Id:
    type: string
    description: SFDC User Id
    required: true